WIDTH = 960
HEIGHT = 640
FPS = 60
CAPTION = "IB Survival Game"

PLAYER_SPEED_MIN = 200
PLAYER_SPEED_MAX = 500
ITEM_WIDTH = 150
ITEM_HEIGHT = 150
STRESS_BURNOUT = 80
STRESS_BURNOUT_TIME_INTERVAL = 5

FONT_DIR = "assets/fonts"
IMAGE_DIR = "assets/images"
SOUND_DIR = "assets/sounds"
DEFAULT_FONT = "pixel.ttf"

